[package]
name = "gnomeengine"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
adw = { package = "libadwaita", version = "0.7", features = ["v1_4"] }
gio = "0.20"
glib = "0.20"
futures-channel = "0.3"
gtk = { package = "gtk4", version = "0.9", features = ["v4_12"] }
gdk = { package = "gdk4", version = "0.9" }
gstreamer = "0.23"
gstreamer-app = "0.23"
gstreamer-pbutils = "0.23"
gstreamer-video = "0.23"
png = "0.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
