[package]
name = "gnomeengine-renderer"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
gtk = { package = "gtk4", version = "0.9", features = ["v4_8"] }
gdk = { package = "gdk4", version = "0.9" }
gdk4-x11 = { version = "0.9" }
gdk4-x11-sys = "0.9"
gio = "0.20"
glib = "0.20"
gstreamer = "0.23"
gstgtk4 = { package = "gst-plugin-gtk4", version = "=0.13.0", features = ["static", "wayland", "x11egl", "x11glx", "dmabuf"] }
